### ISSUE TITLE
Failed to install on linux ubuntu

### ISSUE THREAD

**Issue by Coeur-Digital** [taylorchasewhite/copacetic-frontity#1]
I trying to install your theme on an existing project 
**Ubuntu** 20.04 
**node -v**
v12.18.4
**nvm -v**
0.36.0

I also try with the git clone fail too
```
> npm install @taylorwhite/copacetic-frontity
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@taylorwhite%2fcopacetic-frontity - Not found
npm ERR! 404 
npm ERR! 404  '@taylorwhite/copacetic-frontity@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cc/.npm/_logs/2020-09-28T05_24_05_547Z-debug.log
```
Best regards

**Comment by Coeur-Digital** [comment]
I update the link by  **npm install @taylorwhite/copacetic-frontity-theme**
installation works fine 
i do npx frontity dev and got 
`TypeError: Cannot destructure property 'title' of 'data' as it is undefined.
      at SecondaryPostPreview (webpack-internal:///./node_modules/@taylorwhite/copacetic-frontity-theme/src/components/featured-post/featured-post.js:13:2376)
      at processChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:397:2319)
      at resolve (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:396:122)
      at ReactDOMServerRenderer.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:1199)
      at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:433:55)
      at renderToString (webpack-internal:///./node_modules/react-dom/cjs/react-dom-server.node.development.js:470:116)
      at eval (webpack-internal:///./node_modules/@frontity/core/src/server/index.tsx:53:243)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at eval (webpack-internal:///./node_modules/koa-mount/index.js:16:290)`

**Comment by taylorchasewhite** [comment]
Hmm, thanks for the info, I'm going to look into this today, sorry for the
inconvenience.

**Comment by taylorchasewhite** [comment]
Hey @Coeur-Digital, would you mind doing the following:

- indicating which server/website you're attempting to grab posts from? I'll see if this has something to do with the data coming back and being passed to SecondaryPostPreview (i.e. are there not enough posts or something along those lines and null values aren't correctly handled).
- update to the latest version of taylorchasewhite/copacetic-frontity-theme--Let me know if you still see this issue.

Thanks!

**Comment by robrecord** [comment]
For others coming here, this happens because there are less than 3 posts. You must create at least 3 posts otherwise you get the failure described above. This goes for the Chakra theme too.

> Cannot destructure property 'title' of 'data' as it is undefined.

**Comment by robrecord** [comment]
> For others coming here, this happens because there are less than 3 posts. You must create at least 3 posts otherwise you get the failure described above. This goes for the Chakra theme too.

> Cannot destructure property 'title' of 'data' as it is undefined.
